### ISSUE TITLE
Data error

### ISSUE THREAD

**Issue by sherrychen32** [ericlin79119/3D-point-cloud-generation#1]
Thank you for providing your code and data. But there seems to be some error inside the data. 
I had download the data from [here](https://cmu.app.box.com/s/s4lkm5ej7sh4px72vesr17b1gxam4hgy). But when I run `tar -zxf 3D-PCG-data.tar.gz` it shows the error as following.
`
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
`
I also tried `tar zxvf 3D-PCG-data.tar.gz`, the same error message is shown.

**Comment by chenhsuanlin** [comment]
Hmm that's weird, can you validate if the checksum of your downloaded .tar.gz file matches the below?
`388c1533ea79c229f51497c552926495`
Thanks!

**Comment by sherrychen32** [comment]
The checksum of the file is 282663a16e9ffa5d2eb0dc721de4391292a729b1.

**Comment by chenhsuanlin** [comment]
So it seems like your file is corrupted during the download; if your checksum matches mine then you should be able to decompress.
Can you try downloading by running the below command instead? Hopefully this is more stable.
 `wget https://cmu.box.com/shared/static/s4lkm5ej7sh4px72vesr17b1gxam4hgy.gz`

**Comment by chenhsuanlin** [comment]
Closing this; please feel free to reopen if there are still issues!
