### ISSUE TITLE
Could I run rendering with the different dataset in which the point cloud of scene and camera poses (rotation, translation) are known

### ISSUE THREAD

**Issue by TruongKhang** [ericlin79119/3D-point-cloud-generation#10]
Hello, 

I want to render a depth map. I've already had a 3D point-cloud model and a set of camera poses (quaternion + translation vector). Can I make a change in your code to run with my dataset? 
Hope to hear from you. Thank you so much.

Best,

**Comment by chenhsuanlin** [comment]
Sure, please feel free to clone the repo and make changes according to your own needs.
