### ISSUE TITLE
Conversion to PLY or OBJ?

### ISSUE THREAD

**Issue by aOlmo** [ericlin79119/3D-point-cloud-generation#11]
Sorry if it's a silly question: is there any way to convert the outputs (Z an trans) of the pointcloud to a PLY or OBJ file? 

I think it can be useful for non experts like me who just want to use the code out-of-box for experiments.

**Comment by chenhsuanlin** [comment]
There are several Python libraries for this, e.g. [PyMesh](https://pymesh.readthedocs.io/en/latest/), or you could even write your own OBJ dumper following the [OBJ format](https://en.wikipedia.org/wiki/Wavefront_.obj_file) -- it's human-readable as well.
