### ISSUE TITLE
How to get the depth and depth_fixed8 matrices

### ISSUE THREAD

**Issue by aOlmo** [ericlin79119/3D-point-cloud-generation#12]
The code uses both the `depth` and `depth_fixed8` matrices (that already come pre-rendered in the downloaded data/ folder) to generate the 3D point cloud of an specific `inputRGB` image. Could you please share how you created those matrices so that we can do it for our own 2D images?

Thank you in advance, hope it's not a problem

**Comment by chenhsuanlin** [comment]
You could create random rotation matrices by sampling on the unit sphere in 3D, and that gives you the spherical coordinates. Sampling an additional in-plane rotation gives you a full 3-DoF random rotation matrix. The fixed 8 cameras are simply at the corners of a zero-centered cube.
Hope this helps!
