### ISSUE TITLE
Dear Lin,

### ISSUE THREAD

**Issue by Dandy5721** [ericlin79119/3D-point-cloud-generation#13]
Thanks for providing the code. I need to ask you some questions. 1, Can the model conduct the image  of size 1800*1800? 2, Can I replace this data with my own data, because I can't download your data? 3，Can I add the image registration process (to get a large viewpoint image) after obtaining the 2D images? Thanks for your attention! 

Best regrads,

Tingting Dan

**Comment by chenhsuanlin** [comment]
1. It is possible, but such high resolution would be pretty expensive (in both memory and computation). You'll also need to modify the network architecture accordingly as well.
2. You might need to use a VPN to get around firewalls if you have trouble downloading my data. The link is still active on my side. But using your own datasets is surely possible.
3. I'm not exactly sure what you mean by a viewpoint image?

Please let me know if you have further issues.

**Comment by Dandy5721** [comment]
I am sorry I didn't express Q3 clearly. If we obtain two or more multi-viewpoint image, we can align there images and mosaic them to obtain a complete image, then achieve reconstruction process? Do  I make sense?

**Comment by chenhsuanlin** [comment]
I think you're probably referring to structure from motion? This work is really a learning-based 3D reconstruction method, but I guess it's also possible to use SfM to refine the generated point clouds if multiple views are available.

**Comment by Dandy5721** [comment]
Thank you very much!


| |
dragonproject2017
|
|
邮箱：ddragon_2017@163.com
|

Signature is customized by Netease Mail Master

On 12/18/2019 02:32, Chen-Hsuan Lin wrote:

I think you're probably referring to structure from motion? This work is really a learning-based 3D reconstruction method, but I guess it's also possible to use SfM to refine the generated point clouds if multiple views are available.
