### ISSUE TITLE
Issue with accessing model_normalized.obj

### ISSUE THREAD

**Issue by ashwathym** [ericlin79119/3D-point-cloud-generation#14]
Hi,

I've noticed that both render.py and render_fixed.py try to access a file called 'model_normalized.obj', which is supposed to be under the 'models' directory for each object code in the specified series (for example: '/dataset/ShapeNetCore.v1/03001627/1006be65e7bc937e9141f9b58470d646/models/model_normalized.obj')
But it seems that such a file or directory doesn't exist.

I downloaded the image zip file for the chair synset ( synset id: 03001627) under the ShapeNetCore v1 dataset from shapenet.org.

I'd really like to know how model_normalized.obj is created. Is it supposed to be available in the zip file? Or have I missed out any steps in between scripts/evaluate_dist.sh and ./run.sh 03001627 8?

Any help is highly appreciated. Thanks in advance!

**Comment by ashwathym** [comment]
EDIT: Have I missed out any steps in between scripts/run-compute-error.sh and ./run.sh 03001627 8?

**Comment by chenhsuanlin** [comment]
`model_normalized.obj` comes with ShapeNet v2, so please use ShapeNet v2 if you want to render using this repo (as described in README). Thanks!
