### ISSUE TITLE
CPU Memory usage increase during finetuning

### ISSUE THREAD

**Issue by sherrychen32** [ericlin79119/3D-point-cloud-generation#2]
Hi, 

I tried to train the model by following the instruction. 
But when I tried to fine-tuning with joint 2D optimization using the instruction `scripts/run-finetune.sh`.
However, during training, the memory usage increase rapidly. Is this a normal case? Thank you.
![image](https://user-images.githubusercontent.com/11516050/37567301-f567b0c4-2aff-11e8-947e-f5fa6cd0b9b3.png)

**Comment by chenhsuanlin** [comment]
Yes, unfortunately that happens to me too. I'm guessing this is a memory leakage issue with Tensorflow's `tf.scatter` op, which seems to exist even with the current latest version.
This is why I use a scheduled training script to kill and restart the fine-tuning process. You can modify the script to restart more frequently, it's just that the initialization overhead will be slightly larger.

**Comment by sherrychen32** [comment]
By the way, while using `tf.scatter`, I found that under the tensorflow version 1.0.1, if the index is duplicate, then it might added the values of those indexes, and the output range will be unpredictable. Did you face the same problem?

**Comment by chenhsuanlin** [comment]
I'm not sure I get what you mean, could you perhaps provide a short example? Thanks!

**Comment by chenhsuanlin** [comment]
Closing this for now, please feel free to reopen if you still have issues.
