### ISSUE TITLE
Are gradients wrt output point clouds defined for mask loss ?

### ISSUE THREAD

**Issue by klnavaneet** [ericlin79119/3D-point-cloud-generation#4]
In _transform.py_, _Line 57_, x and y co-ordinates are being converted to int datatype. Since the operation is not differentiable, are gradients for mask loss wrt to point cloud xyz defined ?

**Comment by jiangwei221** [comment]
I'm also having the same question. If we do "round" operation, aren't all the gradients with respect to the X,Y becoming 0s, and only made the gradients valid for Z?

**Comment by chenhsuanlin** [comment]
The mask loss is only directly related to the activity of the generated points, not the coordinates themselves. It is true that gradients are not defined for `round`/`floor`/`ceil`, so the depth gradients will only update in the z direction. Therefore, the method currently relies on optimization from multiple novel viewpoints jointly to update in all possible directions.
