### ISSUE TITLE
Failed to download dataset

### ISSUE THREAD

**Issue by hlesmqh** [ericlin79119/3D-point-cloud-generation#7]
Hello! I've read your paper and have a keen interest on your work. However, I get some problem at the first step. I can't download your dataset by wget or any other way I have. I suspect that may your link is not available now. Would you please give me a new link or any other suggestion to make it? Thank you.

**Comment by chenhsuanlin** [comment]
Can you see if you can access the file from here?
https://cmu.box.com/s/s4lkm5ej7sh4px72vesr17b1gxam4hgy

**Comment by hlesmqh** [comment]
> Can you see if you can access the file from here?
> https://cmu.box.com/s/s4lkm5ej7sh4px72vesr17b1gxam4hgy

Thank your for your reply. I finally find the key problem for me is 'the Great Wall'  QvQ.
Ive find some method to get through it and your codes work well.
Your work is wonderful! Thank you.
