### ISSUE TITLE
Understand geometric transformation functions.

### ISSUE THREAD

**Issue by lkhphuc** [ericlin79119/3D-point-cloud-generation#8]
Hi, thank for the great work.

I would like to understand more about the differentiable transforms functions in transforms.py
As I don't have background in 3D-2D transform matrix, could you give me some helpful links to understand more about it?

Specifically, I would like to know more about `HomMatrix` as in `transParamsToHomMatrix()` function.
Any intro links or correct keywords for Google is appreciated.

**Comment by chenhsuanlin** [comment]
You can take a look at [https://en.wikipedia.org/wiki/Camera_matrix](https://en.wikipedia.org/wiki/Camera_matrix), or search for materials related to camera projection matrices (usually working with homogeneous coordinates).

**Comment by lkhphuc** [comment]
Thanks a lot.
