### ISSUE TITLE
Can't find the dataset link

### ISSUE THREAD

**Issue by BalianWang** [ericlin79119/3D-point-cloud-generation#9]
I couldn't find https://cmu.box.com/shared/static/s4lkm5ej7sh4px72vesr17b1gxam4hgy.gz .
https://cmu.box.com has been changed to https://community.box.com.
Could you update the dataset link? Thank you very much!

**Comment by chenhsuanlin** [comment]
The link still works for me. Do you have a firewall that's blocking your connection or something?

**Comment by BalianWang** [comment]
Thank you!
I am an undergraduate student from mainland China，I think maybe  it's because of the "Network of the Great Wall". I will try something else, but now I'm really despair...
